### ISSUE TITLE
Austline Fabrication Projects page : Bread crumbs should be below the page title

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/TFG-Group#3]
![5](https://cloud.githubusercontent.com/assets/13309806/11334149/fb6e6ca6-9187-11e5-9c3c-73725c4b78f4.png)

**Comment by ravititan** [comment]
The breadcrumbs are above the title in PSD.

**Comment by ravi-josyula** [comment]
As per KB article:
Breadcrumbs will always be below Page/Post Title – this is to enforce consistency with our WooCommerce theme setup.
