### ISSUE TITLE
Admin(SUPPLIER OF INDUSTRIAL EQUIPMENT IN PERTH ) : All items are not displaying when added in admin panel.

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/TFG-Group#31]
Suppose there is any limit for items then newly added item should be displayed as a first item.
![8](https://cloud.githubusercontent.com/assets/13309806/11362602/a766a250-9249-11e5-99cd-44b0d9235960.png)

**Comment by ravititan** [comment]
We have to limit the posts to show only 4 , Now its showing the last added first.
