### ISSUE TITLE
Admin(Our story so far...) : Text should align towards left when video is removed in admin panel

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/TFG-Group#42]
![admin1](https://cloud.githubusercontent.com/assets/13309806/11364561/f901395c-9255-11e5-9291-9cbc4f82fb44.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed
When video image is removed text should align towards left
![1](https://cloud.githubusercontent.com/assets/13309806/11583911/ebcf0320-9a13-11e5-9e14-a9587ab889e8.png)

**Comment by ravititan** [comment]
Tested it and its working fine if we remove the video link from the business details.

**Comment by ravi-josyula** [comment]
Remove the "video image" and check please.
