### ISSUE TITLE
Our profile : Image should be full width as per given PSD in Ipad and Ipad(mini)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/TFG-Group#43]
![pm4](https://cloud.githubusercontent.com/assets/13309806/11364620/5105762c-9256-11e5-890d-1a65d77d8dd0.png)

**Comment by ravititan** [comment]
The width of the image is 100% as per the psd, If we set the height to match with container the image will get stretched (Screenshot).
![carousel-img](https://cloud.githubusercontent.com/assets/13450891/11497428/08dadd8a-983f-11e5-89ca-2bbffa6a5b83.jpg)
