### ISSUE TITLE
Menu : Sub menu's are still displaying while scrolling on Ipad and Ipad(mini)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/TFG-Group#44]
![pm7_001](https://cloud.githubusercontent.com/assets/13309806/11364681/af44a71c-9256-11e5-9048-4186a490b78a.png)

**Comment by ravititan** [comment]
Tested on Ipad and its working fine.

**Comment by ravi-josyula** [comment]
While I'm testing it is bug but now it is fixed
