### ISSUE TITLE
Menu: Sub menus are not styled in Itouch and Samsung E7

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/TFG-Group#47]
![te6](https://cloud.githubusercontent.com/assets/13309806/11393211/2c1451ea-9313-11e5-9996-316280a6707b.png)

**Comment by ravititan** [comment]
Tested in Itouch and Samsung E7 , Sub menus are styled as per the menu design in the psd.

**Comment by ravi-josyula** [comment]
Still bug is not fixed
Second level sub menu is overlapping with first level sub menu.
![tfg](https://cloud.githubusercontent.com/assets/13309806/11582015/14329c34-99fe-11e5-8a29-95fd29541b71.png)
