### ISSUE TITLE
Lead-ins section  : Lead-ins text is getting distorted on IE9, safari and Ipad(mini)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/TFG-Group#8]
![17 ie safari](https://cloud.githubusercontent.com/assets/13309806/11334402/8b305f42-9189-11e5-9d7b-8c3ce1c16a20.png)
![m2](https://cloud.githubusercontent.com/assets/13309806/11334414/9dca50a4-9189-11e5-9ca1-3da9269f0a76.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed in IE9
![2015-12-04_1147](https://cloud.githubusercontent.com/assets/13309806/11583109/0ba12ed4-9a0b-11e5-8091-9e6b8c0b763d.png)

**Comment by ravititan** [comment]
Tested in IE9, Please check the screenshot.
![tfg-screen](https://cloud.githubusercontent.com/assets/13450891/11773365/cd1ef8e8-a24e-11e5-9deb-d4a5ba62c368.jpg)
